language: python
python:
- '3.5'
- '3.6.5'
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
# notifications:
#   email:
#     on_success: change
#     on_failure: always
before_install:
  - pip install codecov
install:
  - pip install ".[test]"
script: pytest
after_success:
  - codecov
